Overall fixes don't worry

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -20,8 +20,6 @@ declare -i sudol=1  # sudo failures allowed (will exit if greater than)
 # TODO: Might wanna learn how to use actual custom args
 log_enable=yes # ha ha yes to be fixed later
 
-[ -e "$DOTFILES/.installed" ] && INSTALLED=yes
-
 # Functions -------------------------------------------------------------------
 
 # Some functions are in the dotfiles script so they can be used
@@ -56,11 +54,13 @@ e_erase()     { echo -en "\033[2K\r"; } # Erase current line
 ### Logging ###
 
 log() {
-	if [ -n "$log_enable" ] && [ -d "$LOG_DIR" ]; then
-		echo -e "[$(date +%H:%M:%S)] - $1" >> "$log_file"; 
-	else
-		echo "WARNING: log location could not be used, logging disabled."
-		log_enable=
+	if [ -n "$log_enable" ]; then
+		if [ -d "$(dirname "$log_file")" ]; then
+			echo -e "[$(date +%H:%M:%S)] - $1" >> "$log_file"; 
+		else
+			echo "WARNING: log location could not be used, logging disabled."
+			log_enable=
+		fi
 	fi
 }
 
@@ -124,15 +124,13 @@ sudo_do() {
 	fi
 		
 	log "[sudo] Executing: $1"
-	
-	# FIXME: try using an eval here, maybe a tee for multiple error output 
-	# (file and terminal), and generally try to fix this mess
 
-	local output
-	[ -z "$log_enabled" ] && output=/dev/null
-	[ -z "$log_enabled" ] && output="$log_file"
+	local output ; output=/dev/null
+	[ -n "$log_enabled" ] && output="$log_file"
 
-	echo "$sudop" | sudo -S 1>> "$output" $1 && return 0 || return 1
+	# shellcheck disable=SC2086
+	# echo "$sudop" | sudo -S 1>>"$output" 2>&1 $1 && return 0 || return 1
+	echo "$sudop" | sudo -S $1 1>>"$output" 2>&1 && return 0 || return 1
 
 	log "[sudo] There has been a sudo error. ($?)"
 	sudof+=1
@@ -284,10 +282,10 @@ prompt_yn 'Reboot?' && sudo_do 'reboot'; echo ''; echo ''
 
 [ -n "$dotbkp" ] && echo "Check backed up file(s) in $DOTFILES/backup"
 
-if [ -z "$INSTALLED" ]; then
+if ! [ -e "$DOTFILES/installed" ]; then
 	echo ''
 	echo 'Since this is your first time running dotfiles...'
-	e_arrow 'A "installed" file has been created. To run dotfiles again as if for the first time, remove it.'
+	e_arrow 'A "installed" file has been created. To run dotfiles again as if for the first time, remove it before running dotfiles again.'
 	e_arrow 'You may need to restart your shell and/or system for some changes to take effect.'
 fi
 
